export const sushi = [
  {
    name: 'Гункан лосось',
    price: 110,
    weight: 40,
    description: 'Лосось, норі, рис, ікра, соус шрірача, японський майонез',
    image: '/src/images/sushi/gunkan-losos.jpg',
    alt: 'Гункан лосось',
  },
  {
    name: 'Гункан креветка',
    price: 100,
    weight: 40,
    description: 'Норі, рис, ікра, креветка, соус шрірача, японський майонез',
    image: '/src/images/sushi/gunkan-krevetka.jpg',
    alt: 'Гункан креветка',
  },
  {
    name: 'Гункан з тунцем і трюфелем',
    price: 135,
    weight: 40,
    description:
      'Норі, рис, японський майонез, бальзамик, трюфельна сальса, цибуля шніт',
    image: '/src/images/sushi/gunkan-tunec-trufel.jpg',
    alt: 'Гункан з тунцем і трюфелем',
  },
  {
    name: 'Гункан тунець спайсі',
    price: 125,
    weight: 40,
    description:
      'Норі, рис, тунець, соус шрірача, японський майонез, кунжутна олія, цибуля шніт,',
    image: '/src/images/sushi/gunkan-tunec-spicy.jpg',
    alt: 'Гункан тунець спайсі',
  },
  {
    name: 'Нігірі вугор',
    price: 115,
    weight: 40,
    description: 'Норі, рис, кунжут, cоус унаги, вугор',
    image: '/src/images/sushi/nigiri-ugor.jpg',
    alt: 'Нігірі вугор',
  },
  {
    name: 'Нігірі вугор',
    price: 190,
    weight: 232,
    description: 'Норі, рис, кунжут, cоус унаги, вугор',
    image: '/src/images/sushi/nigiri-ugor2.jpg',
    alt: 'Нігірі вугор',
  },
  {
    name: 'Гункан вугор',
    price: 115,
    weight: 40,
    description: 'норі, рис, вугор, ікра, соус шрірача, японський майонез',
    image: '/src/images/sushi/nigiri-ugor2.jpg',
    alt: 'Гункан вугор',
  },
  {
    name: 'Нігірі тунець',
    price: 190,
    weight: 40,
    description: 'Рис, тунець',
    image: '/src/images/sushi/nigiri-tunec.jpg',
    alt: 'Нігірі тунець',
  },
];
